ALTER TABLE `paiements` ADD `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE AFTER `montant`; 

CREATE OR REPLACE VIEW view_from_all_demandes AS
	select `demande_p001_s`.`uuid`, `demande_p001_s`.`montant`,`demande_p001_s`.`reference`, `demande_p001_s`.`paiement`, `demande_p001_s`.`denomination_sociale_demandeur` as `demandeur`, `demande_p001_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p001_s`.`created_at` from `demande_p001_s` inner join `procedures` on `procedures`.`uuid` = `demande_p001_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p001_s`.`commune_id`
		UNION
	select `demande_p002_s`.`uuid`, `demande_p002_s`.`montant`,`demande_p002_s`.`reference`, `demande_p002_s`.`paiement`, `demande_p002_s`.`identite` as `demandeur`, `demande_p002_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p002_s`.`created_at` from `demande_p002_s` inner join `procedures` on `procedures`.`uuid` = `demande_p002_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p002_s`.`commune_id`
		UNION
	select `demande_p003_s`.`uuid`,`demande_p003_s`.`montant`, `demande_p003_s`.`reference`, `demande_p003_s`.`paiement`, `demande_p003_s`.`identite` as `demandeur`, `demande_p003_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p003_s`.`created_at` from `demande_p003_s` inner join `procedures` on `procedures`.`uuid` = `demande_p003_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p003_s`.`commune_id`
		UNION
	select `demande_p004_s`.`uuid`, `demande_p004_s`.`montant`,`demande_p004_s`.`reference`, `demande_p004_s`.`paiement`, CONCAT(usagers.nom, " ", usagers.prenom) AS demandeur, `demande_p004_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p004_s`.`created_at` from `demande_p004_s` inner join `procedures` on `procedures`.`uuid` = `demande_p004_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p004_s`.`commune_id` inner join `usagers` on `usagers`.`uuid` = `demande_p004_s`.`usager_id`
		UNION
	select `demande_p005_s`.`uuid`, `demande_p005_s`.`montant`,`demande_p005_s`.`reference`, `demande_p005_s`.`paiement`, `demande_p005_s`.`identite` as `demandeur`, `demande_p005_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p005_s`.`created_at` from `demande_p005_s` inner join `procedures` on `procedures`.`uuid` = `demande_p005_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p005_s`.`commune_id`
		UNION
	select `demande_p006_s`.`uuid`, `demande_p006_s`.`montant`, `demande_p006_s`.`reference`, `demande_p006_s`.`paiement`, CONCAT(usagers.nom, " ", usagers.prenom) AS demandeur, `demande_p006_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p006_s`.`created_at` from `demande_p006_s` inner join `procedures` on `procedures`.`uuid` = `demande_p006_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p006_s`.`commune_id` inner join `usagers` on `usagers`.`uuid` = `demande_p006_s`.`usager_id`
		UNION
	select `demande_p007_s`.`uuid`, `demande_p007_s`.`montant`,`demande_p007_s`.`reference`, `demande_p007_s`.`paiement`, CONCAT(usagers.nom, " ", usagers.prenom) AS demandeur, `demande_p007_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p007_s`.`created_at` from `demande_p007_s` inner join `procedures` on `procedures`.`uuid` = `demande_p007_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p007_s`.`commune_id` inner join `usagers` on `usagers`.`uuid` = `demande_p007_s`.`usager_id`
		UNION
	select `demande_p008_s`.`uuid`, `demande_p008_s`.`montant`, `demande_p008_s`.`reference`, `demande_p008_s`.`paiement`, CONCAT(usagers.nom, " ", usagers.prenom) AS demandeur, `demande_p008_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p008_s`.`created_at` from `demande_p008_s` inner join `procedures` on `procedures`.`uuid` = `demande_p008_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p008_s`.`commune_id` inner join `usagers` on `usagers`.`uuid` = `demande_p008_s`.`usager_id`
		UNION
	select `demande_p0011_s`.`uuid`, `demande_p0011_s`.`montant`, `demande_p0011_s`.`reference`, `demande_p0011_s`.`paiement`, CONCAT(usagers.nom, " ", usagers.prenom) AS demandeur, `demande_p0011_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p0011_s`.`created_at` from `demande_p0011_s` inner join `procedures` on `procedures`.`uuid` = `demande_p0011_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p0011_s`.`commune_id` inner join `usagers` on `usagers`.`uuid` = `demande_p0011_s`.`usager_id`
		UNION
	select `demande_p0012_s`.`uuid`,`demande_p0012_s`.`montant`, `demande_p0012_s`.`reference`, `demande_p0012_s`.`paiement`, CONCAT(usagers.nom, " ", usagers.prenom) AS demandeur, `demande_p0012_s`.`etat`, `procedures`.`code` as `procedure`, `procedures`.`libelle_long` as `procedure_libelle`, `procedures`.`delai`, `services`.`libelle_court` as `direction`, `communes`.`libelle` as `residence`, `demande_p0012_s`.`created_at` from `demande_p0012_s` inner join `procedures` on `procedures`.`uuid` = `demande_p0012_s`.`procedure_id` inner join `services` on `services`.`uuid` = `procedures`.`service_id` inner join `communes` on `communes`.`uuid` = `demande_p0012_s`.`commune_id` inner join `usagers` on `usagers`.`uuid` = `demande_p0012_s`.`usager_id`;
